language: go

go:
  - tip
  - 1.12
  - 1.11.x

os:
  - linux

install:
  - go get -u github.com/mattn/goveralls
  - go get -u github.com/dave/courtney

script:
  - GOOS=linux go build
  - go test -v -parallel 4 -cover
  - courtney -v

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - goveralls -coverprofile=coverage.out -service=travis-ci
